### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by donutloop** [rootsongjc/kubernetes-handbook#110]
Hi there, 

Could you please add an English translation for your book? 

Kind regards,

Donutloop

**Comment by rootsongjc** [comment]
There are 161,311 Chinese words in this book now. If I translate it that's will be a huge work! 😱 Some of the pages are from the official kubernetes doc, so you can read in k8s.io directly. Some pages are my own practices. You can follow my twitter [jimmysongio](https://twitter.com/jimmysongio), all of my tweets are in English. We can touch there. 😄

**Comment by ipochi** [comment]
@rootsongjc 
I agree on the amount of work.

But there is a work around.
I am reading your book via google translate [google does a darn good job of translating] , however some sentences lose their meaning.

Can you maybe use google translate and do a cross verification if the sentence makes sense after translation , that way the corrections would far less than the actual work.

**Comment by rootsongjc** [comment]
@ipochi It’s hard to say, some of pages are from the official kubernetes doc because I am a participant of the work of official kubernetes Chineses edition, some of pages are from the best practice of mine such as the installation and CI/CD, monitoring etc. This book will keep writing in Chinese, if you have any question you can ask me directly from [twitter](https://twitter.com/jimmysongio). Also sometimes I will post in medium in English.
