### ISSUE TITLE
Kubelet service cannot start

### ISSUE THREAD

**Issue by cissyLlaly** [rootsongjc/kubernetes-handbook#2]
When I execute "systemctl start kubelet " the command, the result show "error: failed to run kubelet: cannot create certificate signing request: the server has asked for the client to provide credentials (post certificatesigningrequests.certificates.k8s.io)"
I have update /etc/kubernetes/kubelet  "KUBELET_ARGS", for example: add --tls-cert-file and --tls-private-key-file and other ,but still not get the correct result.
Can somebody help me about the question? thx

**Comment by rootsongjc** [comment]
- Firstly, check the network connection between your kubelet node and master, if the flannel functional ok? Ping pod's IP address from the other node. 
- Secondly, check your token.cvs

**Comment by cissyLlaly** [comment]
Thank you for your reply.
1. The kubelet service and master service  located the same vm.
2. I have checked the token.cvs , the content of file is ",kubelet-bootstrap,10001,"system:kubelet-bootstrap"", I think it is right. And the users:name of the bootstrap.kubeconfig file is also kubelet-bootstrap.
which file should I check?

**Comment by rootsongjc** [comment]
Your `token.cvs` has a mistake.
Run the command in a line:
```
export BOOTSTRAP_TOKEN=$(head -c 16 /dev/urandom | od -An -t x | tr -d ' ')
cat > token.csv <<EOF
${BOOTSTRAP_TOKEN},kubelet-bootstrap,10001,"system:kubelet-bootstrap"
EOF
```
`token.cvs` should like this:
```
a0376b99a9a7091ade8399e9f6fcd808,kubelet-bootstrap,10001,"system:kubelet-bootstrap"
```

**Comment by cissyLlaly** [comment]
When after I execute above command , I get the same content as you offered.

token.cvs is:
b8c4a8343fd4e262234a59f1a8017457,kubelet-bootstrap,10001,"system:kubelet-bootstrap"
And the token of bootstrap.kubeconfig is same with the above.
But the issue still exists.

**Comment by rootsongjc** [comment]
Could you show me your environment, such as flannel config, logs details and differences from my instructions.

**Comment by jinanxiaolaohu** [comment]
遇到相同的问题了 这个里面没有写如何解决啊?

**Comment by zifeiyuk8s** [comment]
我也遇到了

**Comment by zifeiyuk8s** [comment]
[root@node1 ~]# cp ~/.kube/config /etc/kubernetes/kubelet.kubeconfig 
这样解决了，但是往下运行的时候感觉有问题啊
[root@node1 ~]# kubectl get pod -n kube-system -o wide       
No resources found.

**Comment by zifeiyuk8s** [comment]
宋净超，我看到你啦！

**Comment by rootsongjc** [comment]
@zifeiyuk8s 继续运行会有什么问题？

**Comment by zifeiyuk8s** [comment]
i have the same problem

[root@node1 ~]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 六 2017-12-30 10:55:13 CST; 4s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 31297 ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP (code=exited, status=0/SUCCESS)
  Process: 31289 ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 31288 ExecStartPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 31282 ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 31281 ExecStart=/root/local/bin/kubelet --address=192.168.92.10 --hostname-override=192.168.92.10 --pod-infra-container-image=mirrorgooglecontainers/pause-amd64:3.0 --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --cert-dir=/etc/kubernetes/ssl --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/root/local/bin --cluster-dns=10.68.0.2 --cluster-domain=cluster.local. --hairpin-mode hairpin-veth --allow-privileged=true --fail-swap-on=false --logtostderr=true --v=2 (code=exited, status=1/FAILURE)
 Main PID: 31281 (code=exited, status=1/FAILURE)

12月 30 10:55:13 node1 systemd[1]: Failed to start Kubernetes Kubelet.
12月 30 10:55:13 node1 systemd[1]: Unit kubelet.service entered failed state.
12月 30 10:55:13 node1 systemd[1]: kubelet.service failed.

**Comment by zifeiyuk8s** [comment]
but This problem has been solved,try this

[root@node1 ~]# cp ~/.kube/config /etc/kubernetes/kubelet.kubeconfig 
[root@node1 ~]# systemctl status kubelet   
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 六 2017-12-30 11:14:04 CST; 6s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 38492 ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP (code=exited, status=0/SUCCESS)
  Process: 38480 ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 38471 ExecStartPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 38466 ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
 Main PID: 38465 (kubelet)
   Memory: 33.4M
   CGroup: /system.slice/kubelet.service
           └─38465 /root/local/bin/kubelet --address=192.168.92.10 --hostname-override=192.168.92.10 --pod-infra-container-image=mirrorgooglecontainers/pause-am...

12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661156   38465 flags.go:52] FLAG: --eviction-max-pod-grace-period="0"
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661167   38465 flags.go:52] FLAG: --eviction-minimum-reclaim=""
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661181   38465 flags.go:52] FLAG: --eviction-pressure-transition-period="5m0s"
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661191   38465 flags.go:52] FLAG: --eviction-soft=""
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661200   38465 flags.go:52] FLAG: --eviction-soft-grace-period=""
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661209   38465 flags.go:52] FLAG: --exit-on-lock-contention="false"
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661219   38465 flags.go:52] FLAG: --experimental-allocatable-ignore-eviction="false"
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661229   38465 flags.go:52] FLAG: --experimental-allowed-unsafe-sysctls="[]"
12月 30 11:14:04 node1 kubelet[38465]: I1230 11:14:04.661242   38465 flags.go:52] FLAG: --experimental-bootstrap-kubeconfig="/etc/kubernetes/bootstrap.kubeconfig"
12月 30 11:14:04 node1 systemd[1]: Started Kubernetes Kubelet.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by zifeiyuk8s** [comment]
there is no problem ,my k8s is ok
