### ISSUE TITLE
4.1.6-通过 kublet 的 TLS 证书请求问题

### ISSUE THREAD

**Issue by liqingquanliqq** [rootsongjc/kubernetes-handbook#46]
请教一下，通过 CSR 请求后没有看到nodes 和自动生成的 kubelet kubeconfig 文件和公私钥，这是有可能我哪里出错了呢
```
[root@harbor ssl]# kubectl get nodes
No resources found.
[root@harbor ssl]# ls -l /etc/kubernetes/kubelet.kubeconfig
ls: cannot access /etc/kubernetes/kubelet.kubeconfig: No such file or directory
[root@harbor ssl]# ls -l /etc/kubernetes/ssl/kubelet*
-rw------- 1 root root 227 Sep  7 23:04 /etc/kubernetes/ssl/kubelet-client.key
```

**Comment by rootsongjc** [comment]
请查看 API server 和 kubelet 的日志，你这些信息没办法定位问题。

**Comment by beyondli** [comment]
@rootsongjc ，问下kubelet是装在node还是master上？我感觉应该是node上？kubectl get csr 和 kubectl get nodes也都是在node上执行？master上无须安装kubectl？

**Comment by rootsongjc** [comment]
- kubelet是真正运行容器的节点，如果你的master节点同时也要作为worker的话，那么就需要安装kubelet。
- 证书认证的操作都是在master节点上执行的。
- kubectl是跟API server交互的工具，只要能够访问到API server通过鉴权，在任意地方执行都可以。

**Comment by beyondli** [comment]
kubectl get csr 显示No Resources Found，反复配置一直这个问题。。。。
查看messages：
Sep 18 16:54:19 k8node1 systemd: kubelet.service: main process exited, code=exited, status=200/CHDIR
Sep 18 16:54:19 k8node1 systemd: Unit kubelet.service entered failed state.
Sep 18 16:54:19 k8node1 systemd: kubelet.service failed.
Sep 18 16:54:20 k8node1 systemd: kubelet.service holdoff time over, scheduling restart.
Sep 18 16:54:20 k8node1 systemd: Started Kubernetes Kubelet Server.
Sep 18 16:54:20 k8node1 systemd: Starting Kubernetes Kubelet Server...
Sep 18 16:54:20 k8node1 systemd: Failed at step CHDIR spawning /usr/bin/kubelet: No such file or directory
，
由于我启动kubelet经常需要启动好几次才能成功，不知道这个错误是不是指示了启动失败的问题。但启动成功后，马上kubectl get csr，也是报这个错。

不知道一般这种错误可能哪里引起来的，我把node的token。csv， bootstrap。kubeconfig都同步到master上了，。。。。。，sign。。。。

**Comment by rootsongjc** [comment]
你的kubelet的serivce unit配置是不是有问题，日志信息提升找不到`/usr/bin/kubelet`文件。

**Comment by beyondli** [comment]
找到报这个错的原因了，提示找不到/usr/bin/kubelet文件。从配置参数看有这么几种可能
1）kubelet文件本身不在该目录里，这个已经排除
2）对应的kubelet。service中其实还有几个和读写文件相关的
    2.1）$KUBELET_POD_INFRA_CONTAINER，这个挺不好搞的，你给的时速云连接没有/pod-infrastructure:rhel7，因此不能直接设置合适的，我安装了harbor，然后在时速云上找到了另外一个index.tenxcloud.com/eddiewen/pod-infrastructure，感觉是一个东西。但在配置的时候我之前是这样配置的hostname/library/pod-lastest，但一直报错找不到，用docker pull 该地址也是不能pull的，刚才修改成了IP/library/pod-lastest，用docker pull测试可以下载，然后kubelet就正常了，无论启动多少次都么有问题了。
3）还有一个问题，在KUBELET_ARGS参数中有个--kubeconfig， 这个是配置kubelet.kubeconfig，但从你的配置过程看，该文件应该是在server收到CSR后，授权node，node会自动产生的。但在kubelet启动的时候该文件应该还没呢，这个对启动有影响么，是不是会导致	kubectl get	csr产生No	resources	found？？这个我很怀疑，但不知道如何处理了

**Comment by beyondli** [comment]
查阅您的一个md，有如下说明：
BOOTSTRAP_TOKEN 将被写入到 kube-apiserver 使用的 token.csv 文件和 kubelet 使用的 bootstrap.kubeconfig 文件，如果后续重新生成了 BOOTSTRAP_TOKEN，则需要：

更新 token.csv 文件，分发到所有机器 (master 和 node）的 /etc/kubernetes/ 目录下，分发到node节点上非必需；
重新生成 bootstrap.kubeconfig 文件，分发到所有 node 机器的 /etc/kubernetes/ 目录下；
重启 kube-apiserver 和 kubelet 进程；
重新 approve kubelet 的 csr 请求；
=====================
问下重新 approve kubelet 的 csr 请求；这个对应什么命令？？

**Comment by rootsongjc** [comment]
请参考这篇文章：https://jimmysong.io/kubernetes-handbook/guide/tls-bootstrapping.html
签名控制器不会立即签署所有证书请求。相反，它会一直等待直到适当特权的用户被标记为 “已批准” 状态。这最终将是由外部审批控制器来处理的自动化过程，但是对于 alpha 版本的 API 来说，可以由集群管理员通过 kubectl 命令手动完成。

管理员可以使用 kubectl get csr 命令列出所有的 CSR，使用 kubectl describe csr <name> 命令描述某个 CSR的详细信息。在 1.6 版本以前，没有直接的批准/拒绝命令 ，因此审批者需要直接更新 Status 信息（查看如何实现）。此后的 Kubernetes 版本中提供了 kubectl certificate approve <name> 和 kubectl certificate deny <name> 命令。

**Comment by beyondli** [comment]
感谢！通过阅读参考文章
首先回答我自己的一个问题：

-----------------------------------------
在KUBELET_ARGS参数中有个--kubeconfig 对应的文件kubelet.kubeconfig启动就是应该没有的，就是因为如此才会导致通过使用 bootstrap kubeconfig 向 API server 请求客户端证书。这是对的。
-----------------------------------------

但不能回答no resource find， 到底是请求发起了还是压根没发起？再研究下。。。

**Comment by rootsongjc** [comment]
感谢您的建设性提问和深度思考的精神，本人组织了一个微信群，您可以加我微信后我拉你入群，还有一群爱好kubernetes的小伙伴 https://jimmysong.io/about

**Comment by beyondli** [comment]
终于解决了，原来竟然是。。。。。。。。
kubelet service的配置文件中WorkingDirectory=/var/lib/kubelet，这个目录没有创建！！！！！！！
@rootsongjc ，感谢大力支持，继续前进！

**Comment by rootsongjc** [comment]
@beyondli 创建这个目录，我在文档中有说明。
practice/node-installation.md:248:WorkingDirectory=/var/lib/kubelet
practice/node-installation.md:269:注意：`/var/lib/kubelet`需要手动创建。

**Comment by beyondli** [comment]
额，没看到这个文档，建议如果以后有更新计划的话，更新到那个pdf最好啦，估计大家都是照着你那个pdf一路下来的。。。。。

**Comment by rootsongjc** [comment]
@beyondli PDF文档不方便更新，获取最新文档还是通过这个GitHub repo吧，或者查看https://jimmysong.io/kubernetes-handbook，同步更新。

**Comment by rootsongjc** [comment]
@beyondli PDF文档不方便更新，获取最新文档还是通过这个GitHub repo吧，或者查看https://jimmysong.io/kubernetes-handbook，同步更新。

**Comment by beyondli** [comment]
嗯，知道了，非常感谢支持！来自我的华为手机-------- 原始邮件 --------主题：Re: [rootsongjc/kubernetes-handbook] 4.1.6-通过 kublet 的 TLS 证书请求问题 (#46)发件人：Jimmy Song 收件人：rootsongjc/kubernetes-handbook 抄送：beyondli ,Mention @beyondli PDF文档不方便更新，获取最新文档还是通过这个GitHub repo吧，或者查看https://jimmysong.io/kubernetes-handbook，同步更新。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rootsongjc/kubernetes-handbook","title":"rootsongjc/kubernetes-handbook","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rootsongjc/kubernetes-handbook"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rootsongjc in #46: @beyondli PDF文档不方便更新，获取最新文档还是通过这个GitHub repo吧，或者查看https://jimmysong.io/kubernetes-handbook，同步更新。"}],"action":{"name":"View Issue","url":"https://github.com/rootsongjc/kubernetes-handbook/issues/46#issuecomment-330462635"}}}
